CREATE DATABASE IF NOT EXISTS literatuur;

CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(55) NOT NULL,
    author VARCHAR(55) NOT NULL,
    publisher VARCHAR(55) NOT NULL
);

CREATE TABLE IF NOT EXISTS publishers (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(55) NOT NULL
);

CREATE TABLE IF NOT EXISTS authors (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(55) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    username VARCHAR(55) NOT NULL,
    token VARCHAR(255) NOT NULL
);